/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

/**
 *
 * @author UserA
 */
public class basic extends javax.swing.JFrame {

    double var1=0,var2=0;
    char sym='@';
    
    public basic() {
        initComponents();
        
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Display = new javax.swing.JTextField();
        n4 = new javax.swing.JButton();
        n3 = new javax.swing.JButton();
        n7 = new javax.swing.JButton();
        n2 = new javax.swing.JButton();
        n5 = new javax.swing.JButton();
        mod = new javax.swing.JButton();
        n8 = new javax.swing.JButton();
        n9 = new javax.swing.JButton();
        n6 = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        multiplication = new javax.swing.JButton();
        substract = new javax.swing.JButton();
        addition = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        n1 = new javax.swing.JButton();
        n0 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Display.setText("Display");
        Display.setActionCommand("<Not Set>");
        Display.setName(""); // NOI18N
        Display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DisplayMousePressed(evt);
            }
        });
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });
        Display.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                DisplayVetoableChange(evt);
            }
        });
        getContentPane().add(Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 410, 80));

        n4.setText("4");
        n4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n4MouseClicked(evt);
            }
        });
        getContentPane().add(n4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 70, 40));

        n3.setText("3");
        n3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n3MouseClicked(evt);
            }
        });
        n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n3ActionPerformed(evt);
            }
        });
        getContentPane().add(n3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 70, 40));

        n7.setText("7");
        n7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n7MouseClicked(evt);
            }
        });
        getContentPane().add(n7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 70, 40));

        n2.setText("2");
        n2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n2MouseClicked(evt);
            }
        });
        getContentPane().add(n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 70, 40));

        n5.setText("5");
        n5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n5MouseClicked(evt);
            }
        });
        getContentPane().add(n5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 70, 40));

        mod.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        mod.setText("%");
        mod.setInheritsPopupMenu(true);
        mod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modMouseClicked(evt);
            }
        });
        getContentPane().add(mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 70, 40));

        n8.setText("8");
        n8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n8MouseClicked(evt);
            }
        });
        getContentPane().add(n8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 70, 40));

        n9.setText("9");
        n9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n9MouseClicked(evt);
            }
        });
        n9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n9ActionPerformed(evt);
            }
        });
        getContentPane().add(n9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 70, 40));

        n6.setText("6");
        n6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n6MouseClicked(evt);
            }
        });
        getContentPane().add(n6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 70, 40));

        divide.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        divide.setText("/");
        divide.setAlignmentY(0.2F);
        divide.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        divide.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                divideMouseDragged(evt);
            }
        });
        divide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divideMouseClicked(evt);
            }
        });
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });
        getContentPane().add(divide, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 70, 40));

        multiplication.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        multiplication.setText("*");
        multiplication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplicationMouseClicked(evt);
            }
        });
        multiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicationActionPerformed(evt);
            }
        });
        getContentPane().add(multiplication, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 70, 40));

        substract.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        substract.setText("-");
        substract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                substractMouseClicked(evt);
            }
        });
        substract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                substractActionPerformed(evt);
            }
        });
        getContentPane().add(substract, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 70, 40));

        addition.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        addition.setText("+");
        addition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                additionMouseClicked(evt);
            }
        });
        addition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionActionPerformed(evt);
            }
        });
        getContentPane().add(addition, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 70, 130));

        submit.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        submit.setText("=");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 80, 50));

        n1.setText("1");
        n1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n1MouseClicked(evt);
            }
        });
        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });
        getContentPane().add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 70, 40));

        n0.setText("0");
        n0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n0MouseClicked(evt);
            }
        });
        n0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n0ActionPerformed(evt);
            }
        });
        getContentPane().add(n0, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 70, 40));

        clear.setBackground(new java.awt.Color(255, 0, 0));
        clear.setText("C");
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
        });
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 70, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\UserA\\Downloads\\df38145112c182276d09f615b614c885.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 550, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void n9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n9ActionPerformed

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n1ActionPerformed

    private void n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n3ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    private void n2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n2MouseClicked
        
        if(var1==0){
            var1=2;            
        }
        else if(var2==0){
            var2=2;
        }
        else{}
         
    }//GEN-LAST:event_n2MouseClicked

    private void n1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n1MouseClicked
        if(var1==0){
            var1=1;            
        }
        else if(var2==0){
            var2=1;
        }
        else{}
    }//GEN-LAST:event_n1MouseClicked

    private void n3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n3MouseClicked
    if(var1==0){
            var1=3;            
        }
        else if(var2==0){
            var2=3;
        }
        else{}        // TODO add your handling code here:
    }//GEN-LAST:event_n3MouseClicked

    private void n4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n4MouseClicked
        if(var1==0){
            var1=4;            
        }
        else if(var2==0){
            var2=4;
        }
        else{}        // TODO add your handling code here:
    }//GEN-LAST:event_n4MouseClicked

    private void n5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n5MouseClicked
        if(var1==0){
            var1=5;            
        }
        else if(var2==0){
            var2=5;
        }
        else{}        // TODO add your handling code here:
    }//GEN-LAST:event_n5MouseClicked

    private void n6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n6MouseClicked
        if(var1==0){
            var1=6;            
        }
        else if(var2==0){
            var2=6;
        }
        else{}        // TODO add your handling code here:
    }//GEN-LAST:event_n6MouseClicked

    private void n7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n7MouseClicked
        if(var1==0){
            var1=7;            
        }
        else if(var2==0){
            var2=7;
        }
        else{}        // TODO add your handling code here:
    }//GEN-LAST:event_n7MouseClicked

    private void n8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n8MouseClicked
        if(var1==0){
            var1=8;            
        }
        else if(var2==0){
            var2=8;
        }
        else{}        // TODO add your handling code here:
    }//GEN-LAST:event_n8MouseClicked

    private void n9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n9MouseClicked
        if(var1==0){
            var1=9;            
        }
        else if(var2==0){
            var2=9;
        }
        else{}        // TODO add your handling code here:
    }//GEN-LAST:event_n9MouseClicked

    private void n0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n0MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_n0MouseClicked

    private void n0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n0ActionPerformed

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
        Display.setText("put your text here");
    }//GEN-LAST:event_DisplayActionPerformed

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
  
        
        Display.setText(sym+" 000 "+ var1+" 000 "+var2);
        
    }//GEN-LAST:event_submitMouseClicked

    private void modMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modMouseClicked
        sym='%';        // TODO add your handling code here:
    }//GEN-LAST:event_modMouseClicked

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_divideActionPerformed

    private void multiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicationActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_multiplicationActionPerformed

    private void substractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_substractActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_substractActionPerformed

    private void additionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_additionActionPerformed

    private void divideMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divideMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_divideMouseDragged

    private void divideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divideMouseClicked
        sym='/';         // TODO add your handling code here:
    }//GEN-LAST:event_divideMouseClicked

    private void multiplicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicationMouseClicked
        sym='*';         // TODO add your handling code here:
    }//GEN-LAST:event_multiplicationMouseClicked

    private void substractMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_substractMouseClicked
        sym='-';         // TODO add your handling code here:
    }//GEN-LAST:event_substractMouseClicked

    private void additionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_additionMouseClicked
        sym='+';         // TODO add your handling code here:
    }//GEN-LAST:event_additionMouseClicked

    private void DisplayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisplayMousePressed
        
    }//GEN-LAST:event_DisplayMousePressed

    private void DisplayVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_DisplayVetoableChange
    }//GEN-LAST:event_DisplayVetoableChange

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        
        sym='@';
        var1=0;
        var2=0;
                
        
        
    }//GEN-LAST:event_clearMouseClicked

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new basic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Display;
    private javax.swing.JButton addition;
    private javax.swing.JButton clear;
    private javax.swing.JButton divide;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton mod;
    private javax.swing.JButton multiplication;
    private javax.swing.JButton n0;
    private javax.swing.JButton n1;
    private javax.swing.JButton n2;
    private javax.swing.JButton n3;
    private javax.swing.JButton n4;
    private javax.swing.JButton n5;
    private javax.swing.JButton n6;
    private javax.swing.JButton n7;
    private javax.swing.JButton n8;
    private javax.swing.JButton n9;
    private javax.swing.JButton submit;
    private javax.swing.JButton substract;
    // End of variables declaration//GEN-END:variables
}
