/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


package javaapplication2;

/**
 *
 * @author UserA
 */

public class basic extends javax.swing.JFrame {

    double var1=0,var2=0, ans=0;
    String s1="",s2="" , tot="";
    char sym='@';
    boolean equ=false;
    int inc1=1,inc2=1;
    
    public basic() {
        initComponents();
        Display.setHorizontalAlignment(Display.CENTER);
        Display.setText("Enter Your Equation...");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        Display = new javax.swing.JTextField();
        n4 = new javax.swing.JButton();
        n3 = new javax.swing.JButton();
        n7 = new javax.swing.JButton();
        n2 = new javax.swing.JButton();
        n5 = new javax.swing.JButton();
        n8 = new javax.swing.JButton();
        n9 = new javax.swing.JButton();
        n6 = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        multiplication = new javax.swing.JButton();
        substract = new javax.swing.JButton();
        addition = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        n1 = new javax.swing.JButton();
        n0 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(153, 0, 0));
        back.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        back.setForeground(new java.awt.Color(51, 102, 255));
        back.setText("<");
        back.setAlignmentY(0.2F);
        back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        back.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backMouseDragged(evt);
            }
        });
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 70, 40));

        Display.setBackground(new java.awt.Color(204, 204, 204));
        Display.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Display.setForeground(new java.awt.Color(51, 51, 51));
        Display.setText("Enter Your Equation...");
        Display.setActionCommand("<Not Set>");
        Display.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        Display.setName(""); // NOI18N
        Display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DisplayMousePressed(evt);
            }
        });
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });
        Display.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                DisplayVetoableChange(evt);
            }
        });
        getContentPane().add(Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 410, 80));

        n4.setBackground(new java.awt.Color(0, 51, 51));
        n4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        n4.setForeground(new java.awt.Color(204, 204, 204));
        n4.setText("4");
        n4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        n4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n4MouseClicked(evt);
            }
        });
        getContentPane().add(n4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 70, 40));

        n3.setBackground(new java.awt.Color(0, 51, 51));
        n3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        n3.setForeground(new java.awt.Color(204, 204, 204));
        n3.setText("3");
        n3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        n3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n3MouseClicked(evt);
            }
        });
        n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n3ActionPerformed(evt);
            }
        });
        getContentPane().add(n3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 70, 40));

        n7.setBackground(new java.awt.Color(0, 51, 51));
        n7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        n7.setForeground(new java.awt.Color(204, 204, 204));
        n7.setText("7");
        n7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        n7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n7MouseClicked(evt);
            }
        });
        getContentPane().add(n7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 70, 40));

        n2.setBackground(new java.awt.Color(0, 51, 51));
        n2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        n2.setForeground(new java.awt.Color(204, 204, 204));
        n2.setText("2");
        n2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        n2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n2MouseClicked(evt);
            }
        });
        getContentPane().add(n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 70, 40));

        n5.setBackground(new java.awt.Color(0, 51, 51));
        n5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        n5.setForeground(new java.awt.Color(204, 204, 204));
        n5.setText("5");
        n5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        n5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n5MouseClicked(evt);
            }
        });
        getContentPane().add(n5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 70, 40));

        n8.setBackground(new java.awt.Color(0, 51, 51));
        n8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        n8.setForeground(new java.awt.Color(204, 204, 204));
        n8.setText("8");
        n8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        n8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n8MouseClicked(evt);
            }
        });
        getContentPane().add(n8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 70, 40));

        n9.setBackground(new java.awt.Color(0, 51, 51));
        n9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        n9.setForeground(new java.awt.Color(204, 204, 204));
        n9.setText("9");
        n9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        n9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n9MouseClicked(evt);
            }
        });
        n9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n9ActionPerformed(evt);
            }
        });
        getContentPane().add(n9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 70, 40));

        n6.setBackground(new java.awt.Color(0, 51, 51));
        n6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        n6.setForeground(new java.awt.Color(204, 204, 204));
        n6.setText("6");
        n6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        n6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n6MouseClicked(evt);
            }
        });
        getContentPane().add(n6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 70, 40));

        divide.setBackground(new java.awt.Color(0, 0, 51));
        divide.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        divide.setForeground(new java.awt.Color(51, 102, 255));
        divide.setText("/");
        divide.setAlignmentY(0.2F);
        divide.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        divide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        divide.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        divide.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                divideMouseDragged(evt);
            }
        });
        divide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divideMouseClicked(evt);
            }
        });
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });
        getContentPane().add(divide, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 70, 40));

        multiplication.setBackground(new java.awt.Color(0, 0, 51));
        multiplication.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        multiplication.setForeground(new java.awt.Color(51, 102, 255));
        multiplication.setText("*");
        multiplication.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        multiplication.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        multiplication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplicationMouseClicked(evt);
            }
        });
        multiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicationActionPerformed(evt);
            }
        });
        getContentPane().add(multiplication, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 70, 40));

        substract.setBackground(new java.awt.Color(0, 0, 51));
        substract.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        substract.setForeground(new java.awt.Color(51, 102, 255));
        substract.setText("-");
        substract.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        substract.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        substract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                substractMouseClicked(evt);
            }
        });
        substract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                substractActionPerformed(evt);
            }
        });
        getContentPane().add(substract, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 70, 40));

        addition.setBackground(new java.awt.Color(0, 0, 102));
        addition.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        addition.setText("+");
        addition.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        addition.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                additionMouseClicked(evt);
            }
        });
        addition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionActionPerformed(evt);
            }
        });
        getContentPane().add(addition, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 70, 130));

        submit.setBackground(new java.awt.Color(102, 102, 102));
        submit.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(0, 0, 0));
        submit.setText("=");
        submit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 80, 50));

        n1.setBackground(new java.awt.Color(0, 51, 51));
        n1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        n1.setForeground(new java.awt.Color(204, 204, 204));
        n1.setText("1");
        n1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        n1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n1MouseClicked(evt);
            }
        });
        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });
        getContentPane().add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 70, 40));

        n0.setBackground(new java.awt.Color(0, 51, 51));
        n0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        n0.setForeground(new java.awt.Color(204, 204, 204));
        n0.setText("0");
        n0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        n0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n0MouseClicked(evt);
            }
        });
        n0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n0ActionPerformed(evt);
            }
        });
        getContentPane().add(n0, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 70, 40));

        clear.setBackground(new java.awt.Color(51, 0, 0));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(204, 204, 204));
        clear.setText("C");
        clear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.black));
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
        });
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 70, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/1330535.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void updateDis(){
        
        Display.setHorizontalAlignment(Display.CENTER);
        
        if(s1=="" && s2=="" && sym=='@'){
            Display.setText("Enter Your Equation...");
        }
        
        if(s1=="" && sym!='@'){
            
            sym='@';
        }
        if(s1!=""){
            
            Display.setText(s1);
        }
        if(s1!="" && sym!='@'){
            Display.setText(s1+" "+sym );
        }
        if(s1!="" && sym!='@' && s2!=""){
            Display.setText(s1+" "+sym+" "+s2 );
        }
        
        if(s1!="" && sym!='@' && s2!="" && equ){
            double ans=getAns();
            Display.setText(s1+" "+sym+" "+s2 +" = "+String. format("%.2f", ans));
            equ=false;
        }        
    }
       
    private double getAns(){
        
       double ans=0; 
       int a= Integer.valueOf(s1);
       int b= Integer.valueOf(s2);
       
       if(sym=='+'){
           ans=a+b;
       }
       if(sym=='-'){
           ans=a-b;
       }
       if(sym=='*'){
           ans=a*b;
       }
       if(sym=='/'){
           ans=a*1.0/b*1.0;
       }
       return ans;   
    
    }
    
    private void getVar(String s){
            
        if(sym=='@'){
            s1=s1+s;
            updateDis();
        }
        else if(s2==null){
            updateDis();
        }
        else{
            s2=s2+s;
            updateDis();
        }
        
        
        
         updateDis();
    }
    
    /*private void ans(){
    
        if(var1!=0 && var2!=0 && sym!='@'){
            
            if(sym=='+'){
                ans=var1+var2;
            }
            else if(sym=='-'){
                ans=var1-var2;
            }
            else if(sym=='*'){
                ans=var1*var2;
            }
            else if(sym=='/'){
                ans=var1/var2;
            }
            if(sym=='%'){
                int x = (int) var1;
                int y = (int) var2;
                
                ans=x%y;
            }
            
        }
    
    }*/
    
    private void n9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n9ActionPerformed

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n1ActionPerformed

    private void n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n3ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    private void n2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n2MouseClicked
        
        getVar("2");
         
    }//GEN-LAST:event_n2MouseClicked

    private void n1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n1MouseClicked
        getVar("1");
    }//GEN-LAST:event_n1MouseClicked

    private void n3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n3MouseClicked
        getVar("3");      // TODO add your handling code here:
    }//GEN-LAST:event_n3MouseClicked

    private void n4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n4MouseClicked
       getVar("4");       // TODO add your handling code here:
    }//GEN-LAST:event_n4MouseClicked

    private void n5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n5MouseClicked
        getVar("5");       // TODO add your handling code here:
    }//GEN-LAST:event_n5MouseClicked

    private void n6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n6MouseClicked
        getVar("6");      // TODO add your handling code here:
    }//GEN-LAST:event_n6MouseClicked

    private void n7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n7MouseClicked
        getVar("7");      // TODO add your handling code here:
    }//GEN-LAST:event_n7MouseClicked

    private void n8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n8MouseClicked
        getVar("8");        // TODO add your handling code here:
    }//GEN-LAST:event_n8MouseClicked

    private void n9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n9MouseClicked
        getVar("9");       // TODO add your handling code here:
    }//GEN-LAST:event_n9MouseClicked

    private void n0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n0MouseClicked
        getVar("0");// TODO add your handling code here:
    }//GEN-LAST:event_n0MouseClicked

    private void n0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n0ActionPerformed

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
        
    }//GEN-LAST:event_DisplayActionPerformed

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        
        equ=true;
        updateDis();
        
        
    }//GEN-LAST:event_submitMouseClicked

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_divideActionPerformed

    private void multiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicationActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_multiplicationActionPerformed

    private void substractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_substractActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_substractActionPerformed

    private void additionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_additionActionPerformed

    private void divideMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divideMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_divideMouseDragged

    private void divideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divideMouseClicked
        sym='/'; 
        updateDis();        // TODO add your handling code here:
    }//GEN-LAST:event_divideMouseClicked

    private void multiplicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicationMouseClicked
        sym='*';
        updateDis();// TODO add your handling code here:
    }//GEN-LAST:event_multiplicationMouseClicked

    private void substractMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_substractMouseClicked
        sym='-';
        updateDis();// TODO add your handling code here:
    }//GEN-LAST:event_substractMouseClicked

    private void additionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_additionMouseClicked
        sym='+';
        updateDis();// TODO add your handling code here:
    }//GEN-LAST:event_additionMouseClicked

    private void DisplayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisplayMousePressed
        
    }//GEN-LAST:event_DisplayMousePressed

    private void DisplayVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_DisplayVetoableChange
    }//GEN-LAST:event_DisplayVetoableChange

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        
        sym='@';
        s1="";
        s2="";
         updateDis();
        
        
    }//GEN-LAST:event_clearMouseClicked

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void backMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseDragged

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        
        if(s1!="" && sym=='@' && s2==""){
            s1=Back.remLast(s1);
            updateDis();
        }
        if(s1!="" && sym!='@' && s2==""){
            sym='@';
            updateDis();
        }
        if(s1!="" && sym!='@' && s2!=""){
            s2=Back.remLast(s2);
            updateDis();
        }
        
        
        
    }//GEN-LAST:event_backMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new basic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Display;
    private javax.swing.JButton addition;
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JButton divide;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton multiplication;
    private javax.swing.JButton n0;
    private javax.swing.JButton n1;
    private javax.swing.JButton n2;
    private javax.swing.JButton n3;
    private javax.swing.JButton n4;
    private javax.swing.JButton n5;
    private javax.swing.JButton n6;
    private javax.swing.JButton n7;
    private javax.swing.JButton n8;
    private javax.swing.JButton n9;
    private javax.swing.JButton submit;
    private javax.swing.JButton substract;
    // End of variables declaration//GEN-END:variables
}
